# .coderabbit.yaml
# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
language: "pt-BR"
tone_instructions: ""
early_access: false
enable_free_tier: true
# =============================================================================
# REVIEWS
# =============================================================================
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: "warning"
      threshold: 80
    title:
      mode: "warning"
      requirements: ""
    description:
      mode: "warning"
    issue_assessment:
      mode: "warning"
  tools:
    # Python tools (API)
    ruff:
      enabled: true
    pylint:
      enabled: true
    flake8:
      enabled: true

    # JavaScript/TypeScript tools (Website)
    eslint:
      enabled: true
    biome:
      enabled: true
    oxc:
      enabled: true

    # Documentation and markup
    markdownlint:
      enabled: true
    htmlhint:
      enabled: true

    # Configuration files
    yamllint:
      enabled: true
    dotenvLint:
      enabled: true

    # Security
    osvScanner:
      enabled: true

    # Infrastructure (Docker, GitHub Actions)
    hadolint:
      enabled: true
    actionlint:
      enabled: true

    # Disabled tools (not relevant for this project)
    # Note: These tools are disabled by simply not including them in the active list above
# =============================================================================
# CHAT
# =============================================================================
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: "auto"
    linear:
      usage: "auto"
# =============================================================================
# KNOWLEDGE BASE
# =============================================================================
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    usage: "auto"
    project_keys: []
  linear:
    usage: "auto"
    team_keys: []
  pull_requests:
    scope: "auto"
  mcp:
    usage: "auto"
    disabled_servers: []
# =============================================================================
# CODE GENERATION
# =============================================================================
code_generation:
  docstrings:
    language: "pt-BR"
    path_instructions: []
  unit_tests:
    path_instructions: []
